### ISSUE TITLE
Tail/last call optimisation, tail recursion elimination, whatever, it's not working

### ISSUE THREAD

**Issue by infradig** [infradig/trealla#173]

**Comment by triska** [comment]
Regarding terminology, I recommend to call it **tail call optimisation**, assuming of course that's what you are aiming for.

A call in a tail position means every last goal in clause, *and also* more generally every goal after which nothing else needs to be derived in a clause. For example, the last goal in the final branch of a *disjunction* is a call in a tail position. For instance, if we have a predicate `p/0` defined as:

<pre>
p :-
        (   a,
            b
        ;   c,
            <b>d</b>
        ).
</pre>

Then the *last* goal in the clause body is the *disjunction* `(;)/2`, a meta-predicate that takes two goals as arguments.

Of these goals, the final alternative is a conjunction with two goals `c/0` and `d/0`, and of these goals, `d` is in a *tail position*, and so tail call optimisation can be applied: The stack frame of `p` can be deallocated *before* `d` is invoked, because when that point is reached, there is nothing else left to do in that clause except for proving&nbsp;`d`, and so the stack frame can be deallocated and execution can "jump" to&nbsp;`d`.

In the special case where a goal in a tail position refers to the same predicate that is being defined, it is also called tail *recursion* optimisation, because then the general method of tail call optimisation is applied to a recursive&nbsp;call. In the specific (and very common) case where tail call optimisation is applied to the last goal of a clause, it is also called *last* call optimisation.

**Comment by infradig** [comment]
I use TCO internally. When it stopped I don't yet know, as I just noticed.

**Comment by infradig** [comment]
A flag was reversed. Fixed.
