### ISSUE TITLE
Attributed variables (with SICStus interface)

### ISSUE THREAD

**Issue by infradig** [infradig/trealla#184]
The basics of this is now working... [see](https://www.metalevel.at/prolog/attributedvariables)

The new library/freeze.pl implelements M:verify_attributes/3. The unit tests for freeze/2 in tests/tests/test069.pl all pass.

There are more predicates to implement and I haven't tried anything more complex than freeze yet, so no doubt (much) more work will be required.

**Comment by infradig** [comment]
Note: this implementation of freeze is considerable slower than the old way with the dedicated freeze slot. It's been useful though for development. It might pay to go back to how it was, down the track.

**Comment by pmoura** [comment]
I'm trying the Logtalk `examples/attvars` by modifying its driver files to load and test with v1.8.0-1-g78527. The following query is required before loading the example `loader.lgt` or `tester.lgt` files:

```text
?- use_module(library(atts)).
```

But all tests fail:

```text
?- {tester}.
% 
% tests started at 2021-03-30, 09:23:48
% 
% running tests from object tests
% file: /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt
% 
!     attvars_1: failure (in 0.00014710426330566406 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error("ab"),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt between lines 0-1
!     attvars_2: failure (in 4.8875808715820312e-05 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error("ab"),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt between lines 1-2
!     attvars_3: failure (in 4.7206878662109375e-05 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error("abc"),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt at or above line 2
!     attvars_4: failure (in 8.9168548583984375e-05 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error("ab"),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt between lines 0-1
!     attvars_5: failure (in 7.2002410888671875e-05 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error([1,2]),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt between lines 1-2
!     attvars_6: failure (in 5.8650970458984375e-05 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error([1,2,3]),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt at or above line 2
!     attvars_7: failure (in 5.1021575927734375e-05 seconds)
!       test goal throws an error but should have succeeded: error(uninstantiation_error("abc"),'$get_attrs'/2)
!       in file /Users/pmoura/Documents/Logtalk/logtalk3/examples/attvars/tests.lgt between lines 2-4
% 
% 7 tests: 0 skipped, 0 passed, 7 failed
% completed tests from object tests
% 
% no code coverage information collected
% tests ended at 2021-03-30, 09:23:48
% 
```

The issue here may be that in other Prolog systems the equivalent to the `'$get_attrs'/2` internal predicate fail when the first argument is bound?

**Comment by infradig** [comment]
Too soon!

**Comment by infradig** [comment]
I'll get another run at it tomorrow, hopefully get some examples working.

**Comment by infradig** [comment]
Pushed some changes to devel. The third example at
<https://www.metalevel.at/prolog/attributedvariables> now works (replacing
'#=' by 'is)...


:- module(attrmod, []).
:- use_module(library(atts)).
:- attribute a/1.

verify_attributes(Var, Value, []) :-

get_attr(Var, attrmod, a(n(A))),

get_attr(Value, attrmod, a(n(B))),

C is A + B,

put_attr(Value, attrmod, a(n(C))).


then..

$ tpl attrmod.pl
Trealla Prolog (c) Infradig 2020, v1.8.0-5-g819f2
?- attrmod:put_atts(X, a(n(1))), attrmod:put_atts(Y, a(n(2))), X=Y,
attrmod:get_atts(Y, a(n(N))).
Y = X,
N = 3 .
?-


Need to do M:attribute_goals/1

**Comment by infradig** [comment]
Pushed some changes to devel. The third example [at](https://www.metalevel.at/prolog/attributedvariables) now works (replacing
'#=' by 'is)...

```
  :- module(attrmod, []).
  :- use_module(library(atts)).
  :- attribute a/1.

  verify_attributes(Var, Value, []) :-
    get_attr(Var, attrmod, a(n(A))),
    get_attr(Value, attrmod, a(n(B))),
    C is A + B,
    put_attr(Value, attrmod, a(n(C))).
```

then

```
  $ tpl attrmod.pl
  Trealla Prolog (c) Infradig 2020, v1.8.0-5-g819f2
  ?- attrmod:put_atts(X, a(n(1))), attrmod:put_atts(Y, a(n(2))), X=Y,
  attrmod:get_atts(Y, a(n(N))).
  Y = X,
  N = 3 .
  ?-
```

Need to do M:attribute_goals/1

**Comment by infradig** [comment]
The next & last example seems to work too now...

```
verify_attributes(Var, Other, []) :-
        (   get_atts(Var, domain(Dom1)) ->
            (   var(Other),
                get_atts(Other, domain(Dom2)) ->
                ord_intersection(Dom1, Dom2, Dom),
                dif(Dom, []),
                (   Dom = [Value] ->
                    Other = Value
                ;   put_atts(Other, domain(Dom))
                )
            ;   ord_memberchk(Other, Dom1)
            )
        ;   true
        ).

```

Although I had to borrow library/dif.pl from Scryer.

```
$ tpl attrmod.pl
Trealla Prolog (c) Infradig 2020, v1.8.0-5-g819f2
?- attrmod:domain(X, [a,b,c,d]), attrmod:domain(Y, [c,d,e,f]), X=Y, attrmod:get_atts(Y,domain(L)).
Y = X,
L = "cd" 
; false.
?- 

```

**Comment by triska** [comment]
If the intersection is a single element, then the variable is *unified* with that element, since that is the only value it can assume. Therefore, we have:

<pre>
<b>?- attrmod:domain(X, [a,b,c]), attrmod:domain(Y, [c,d,e]), X=Y.</b>
   X = c, Y = c.
</pre>

Hence, in a query analogous to the one you posted, `get_atts/2` is called in a case where the first argument is not a variable, and we do not expect that to yield attributes.

**Comment by infradig** [comment]
Thanks Markus, it's obvious now that you point it out!

**Comment by triska** [comment]
As an interesting aside, unexpected instantiation (exactly as we saw here) is one of the most frequent sources of errors when implementing constraint solvers.

Realistically, nobody is able to think through all cases that can arise in constraint solvers. So, exactly like in this query, programmers are likely to use `get_atts/2` on arguments that are (unexpectedly) no longer variables when the goal is invoked within propagators, simply because a propagation has occurred that the implementor had not anticipated.

For this reason, it is so important that the interface a Prolog system provides helps to prevent such mistakes as best as it can. I find it great that you have chosen to implement the SICStus interface, which works to our advantage in this case because it first undoes the created bindings, leaving more arguments that are certainly variables when the hooks are invoked, and that helps to reduce such mistakes. It takes a bit more work for the implementor, and in turn makes the implementation of all constraint solvers a lot easier for all contributors.

**Comment by infradig** [comment]
Thanks, also my fault for not implementing attibute_goals//1 first, I would
not have needed to use get_atts to see the results if I had.

On a side note, I borrowed Scryer's dif.pl for these tests. I was looking
at SWI's dif.pl which you co-authored and I notice it is considerably more
complex and larger. Yet Scryer's has presumably been found adequate for the
task so far?

**Comment by triska** [comment]
The complexity in SWI aims to reduce the number of remaining `dif/2` goals so that the answer is in a sense minimal. 

For example, with SWI, we have:

<pre>
<b>?- dif(f(g(X),Y), f(X,Y)).</b>
dif(X, g(X)).
</pre>

While we have in Scryer the "mindless" answer:

<pre>
<b>?- dif(f(g(X),Y), f(X,Y)).</b>
   dif:dif(f(g(X),Y),f(X,Y)).
</pre>

Obviously, the answer from SWI is preferable because it is more readable, and also because it has reduced the constraints to their essence, and that may in turn also improve computation speed when the remaining constraints need to be checked.

On the other hand, who really needs this? The most needed use of `dif/2` is in my experience to express for example "This node in our graph traversal algorithm has not yet been encountered", best expressed with:

<pre>
maplist(dif(Node), Hs)
</pre>

where `Hs` is the history of nodes that were already visited.

Even though `dif/2` was available already in the very first Prolog system (Prolog 0), subsequent Prolog implementations often failed to provide it, and as a result we will be faced for a few more decades with beginners who write this as:

<pre>
\+ member(Node, Hs)
</pre>

and then wonder why this fails to satisfy the most elementary logical properties. Case in point: https://old.reddit.com/r/prolog/comments/mfmy5e/member2_behavior/gsoqf0q/, a question from 3 days ago from a Prolog beginner:

<blockquote>
In my naive mind, <b>the semantics of such statements should not depend on ordering.</b>
</blockquote>

Yes, absolutely, you only have to keep to the pure monotonic core of Prolog, which now increases in implementations again after decades of stagnation and setbacks.

Comparison:

<pre>
<b>?- \+ member(Node, Hs).</b>
false.
</pre>

and:

<pre>
<b>?- maplist(dif(Node), Hs).</b>
   Hs = []
;  Hs = [_A], dif:dif(Node,_A)
;  Hs = [_A,_B], dif:dif(Node,_A), dif:dif(Node,_B)
;  Hs = [_A,_B,_C], dif:dif(Node,_A), dif:dif(Node,_B), dif:dif(Node,_C)
;  ...
</pre>


In fact, even more frequently needed than `dif/2` is `if_/3` from `library(reif)`, because with `if_/3`, we can finally implement pure and monotonic versions of predicates that are now commonly called `include/3` and `exclude/3`, which are *incomplete* and therefore prevent logical reasoning about your code.

For example, in SWI, we have:

<pre>
<b>?- include(=(3), [A,B,C], Ls).</b>
A = B, B = C, C = 3,
Ls = [3, 3, 3].
</pre>

and therefore:

<pre>
<b>?- include(=(3), [A,B,C], Ls), B = 2.</b>
false.
</pre>

But on the other hand, **a more specific query succeeds**:

<pre>
?- B = 2, include(=(3), [A,B,C], Ls), B = 2.
B = 2,
A = C, C = 3,
Ls = [3, 3].
</pre>

This is not monotonic, and therefore prevents declarative debugging, automated reordering of goals, the application of alternative execution strategies etc.

This problem never happens with `tfilter/3` from `library(reif)`, which is based on `if_/3`, because `tfilter/3` correctly lists *all cases that can arise*:

<pre>
<b>?- tfilter(=(3), [A,B,C], Ls).</b>
   Ls = [3,3,3], A = 3, B = 3, C = 3
;  Ls = [3,3], A = 3, B = 3, dif:dif(3,C)
;  Ls = [3,3], A = 3, C = 3, dif:dif(3,B)
;  Ls = [3], A = 3, dif:dif(3,B), dif:dif(3,C)
;  Ls = [3,3], B = 3, C = 3, dif:dif(3,A)
;  Ls = [3], B = 3, dif:dif(3,A), dif:dif(3,C)
;  Ls = [3], C = 3, dif:dif(3,A), dif:dif(3,B)
;  Ls = [], dif:dif(3,A), dif:dif(3,B), dif:dif(3,C).
</pre>

And at the same time, it is *deterministic* in cases where no alternatives remain:

<pre>
<b>?- tfilter(=(3), [1,2,3], Ls).</b>
   Ls = [3].
</pre>

I think `dif/2` was comparatively neglected in practice also because `dif/2` alone does not let you implement `tfilter/3` efficiently (i.e., deterministically). However, now we have `library(reif)`, and this solves such problems once and for all, combining efficiency with generality.

The answer minimization I mentioned above is nice to have, and may be useful for example for `library(diadem)`, to make answers more readable especially when code is reasoned about automatically.

**Comment by infradig** [comment]
Thankyou for a very authoritative answer.

**Comment by triska** [comment]
You are welcome, thank you a lot for working on support for constraints!

If it helps: *Every* version of `dif/2` is better than nothing! Having `dif/2` available, even if it is very simplistic at first, is great to easily obtain more general programs with Trealla Prolog, and wider use of `dif/2` will motivate also other systems to provide it.

In systems that do not support constraints, `dif/2` can be safely approximated with [`iso_dif/2`](https://stackoverflow.com/questions/20223390/prolog-a-person-is-a-sibling-of-himself/20238931#20238931). This does not need constraints at all, and still retains soundness by throwing an *instantiation error* if insufficient information is available to give a definitive answer at this point.

**Comment by infradig** [comment]
Yes, that works with the domain example. I'll include it for now until
something better. The SWI dif/2 only seems to require unifiable/3 to be
usable (unless I missed something else) so I I might look into that.

**Comment by infradig** [comment]
Markus, a quick question. Given...

$ scryer
?- use_module(library(clpb)).
   true.
?- sat(A#B).
   clpb:sat(A=\=B).

Where does that last line come from? The **clpb:sat(A=\=B)** bit?

I gather it's from the 2 solutions for XOR, being mutually exclusive, but where is that symbolically generated in clpb.pl?

I have CLP(B) somewhat partially working in Trealla.

Thanks.

**Comment by triska** [comment]
This is from the DCG nonterminal **`attribute_goals/1`** in `library(clpb)`.

The most important building block for this mechanism is the predicate **`copy_term/3`** which must be provided by the Prolog system. It copies a term (the copy has no attributes attached!), and also yields a list of goals that, when posted, *instantiate equivalent attributes on the copy*.

You can use `copy_term/3` in Scryer Prolog to study examples of how it works. For example:

<pre>
<b>?- sat(A#B), copy_term([A,B], Copy, Gs).</b>
   Copy = [_A,_B], Gs = [clpb:sat(_A=\=_B)].
</pre>

Note how the copied variables `_A` and `_B` have no attributes attached, and that calling the goals in `Gs` with `maplist(call, Gs)` reinstates attributes on them so that they are in the same relation as the original variables `A` and `B`.

When, during copying, `copy_term/3` encounters a variable that has attributes attached, it asks the involved constraint solver for residual goals that are equivalent to the attributes. It does that by invoking `attribute_goals//1` in the relevant module, using the attributed variable as the single argument of the nonterminal.

Thus, the constraint solver has a chance to provide a more readable list of goals, more readable than simply stating a `put_atts/2` goal which "blindly" attaches the needed attribute on the copy.

The toplevel then uses *this very mechanism* (i.e., `copy_term/3`) to get all relevant residual goals, and simply shows the obtained goals as answer. Note how `copy_term/3` can be reliably used to test *whether* this projection works as intended, whereas the toplevel output cannot be easily tested. Therefore, it is good that its impure portions (i.e., writing text on the terminal) are kept as simple and minimal as possible, while the actual logic resides in `copy_term/3` and the involved `attribute_goals//1` nonterminals in constraint solvers which can be readily tested by Prolog queries.

In fact, in the above example, Scryer Prolog *incorrectly* omits the remaining residual goals on `A` and `B`: It should also emit `sat(A=\=B).` as an additional goal in the answer. I will file an issue for this in the Scryer repository. Such mistakes can currently only be found manually, because the toplevel output only appears on the terminal and cannot be easily tested systematically. An ideal toplevel would be implemented in Prolog, in such a way that also the output can be easily tested. `phrase_to_stream/2` as described in #159 would be useful for this, so that we can describe the entire output as a list of characters, and at the same time efficiently write it without manifesting the entire output in memory.

**Comment by infradig** [comment]
Ok thanks, much to think on.

**Comment by triska** [comment]
With the right building blocks in place, `copy_term/3` can be quite easily implemented in Prolog, I think this is a good goal: Think about which simple primitives must be provided by the engine so that you can implement as much as possible in Prolog, maybe with a few custom internal predicates, for example so that you can quickly fetch all attributed variables from a term, and then invoke `attribute_goals//1` in all relevant modules.

You can use `findall/3` to copy a term, remove all its attributes, and (because `findall/3` backtracks and therefore *undoes* the removal of attributes) *still retain* all attributes on the original term when this gathering of residual goals is finished. For instance, if `findall/3` is implemented correctly, the following general pattern will automatically create an unattributed copy of `Term` and retain all attributes on the original term:

<pre>
findall(Term-Gs,
        ( phrase(gather_all_residual_goals(Term), Gs),
          delete_all_attributes(Term)
        ),
        [Copy-Gs])
</pre>

**Comment by infradig** [comment]
I'll keep chipping away at it.

**Comment by UWN** [comment]
@infradig:

> The SWI dif/2 only seems to require unifiable/3 to be usable (unless I missed something else) so I I might look into that.
> […](#)

Just one more remark about the difference between SWI and the [ideal](https://github.com/mthom/scryer-prolog/issues/135#issuecomment-488348886) for Scryer.

Scryer:

```
?- freeze(X,X=b), dif(X,a).
   freeze:freeze(X,user:(X=b)).
?- X in 1..2, Y in 3..4, dif(X, Y).
   clpz:(X in 1..2), clpz:(Y in 3..4).
```

SWI:

```
?- freeze(X,X=b), dif(X,a).
freeze(X, X=b),
dif(X, a).

?- X in 1..2, Y in 3..4, dif(X, Y).
X in 1..2,
dif(X, Y),
Y in 3..4.
```

So effectively also other contraints are taken into account in Scryer and thus unnecessary goals are removed, [not always](https://github.com/mthom/scryer-prolog/issues/1010).

**Comment by UWN** [comment]
@triska:

> Obviously, the answer from SWI is preferable because it is more readable

But there are also cases of SWI's simplification that [users find confusing](https://stackoverflow.com/q/65381805/772868). SICStus does no such simplifications and they have dif/2 since 1987.

**Comment by infradig** [comment]
Markus, I am looking at CLP(B)...

~/trealla (devel) $ swipl
?- use_module(library(clpb)).
true.
?- taut(_A ^ (X=\=_A*Y#Y) =:= X + Y, T).
T = 1,
sat(_A=:=_A),
sat(X=:=X),
sat(Y=:=Y).

*Seems good.*

~/trealla (devel) $ tpl
?- use_module(library(clpb)).
true.
?- taut(_A ^ (X=\=_A*Y#Y) =:= X + Y, T).
false.
?-

*Oops, have I done something wrong?*

But then...

~/trealla (devel) $ scryer
?- use_module(library(clpb)).
   true.
?- taut(_A ^ (X=\=_A*Y#Y) =:= X + Y, T).
false.

*Same!*

The clpb.pl I am testing in Trealla is the Scryer one.

**Comment by triska** [comment]
This is definitely a mistake somewhere, I have filed https://github.com/mthom/scryer-prolog/issues/1148 for it in Scryer Prolog. Thank you a lot for reporting this issue!

**Comment by UWN** [comment]
UWN_open
