### ISSUE TITLE
deep taxonomy use case gives segmentation fault

### ISSUE THREAD

**Issue by josd** [infradig/trealla#215]
With Trealla Prolog (c) Infradig 2020-2021, v1.9.39-6-g421c7
and https://github.com/josd/eye/blob/master/two/dt.pl
the following command line
```
$ tpl -g test dt.pl
```
gives
```
type(i,n1).
type(i,n10).
type(i,n100).
type(i,n1000).
type(i,n10000).
Segmentation fault
```
The expected result should be something like
```
type(i,n1).
type(i,n10).
type(i,n100).
type(i,n1000).
type(i,n10000).
type(i,i10000).
type(i,j10000).
```

**Comment by infradig** [comment]
So this was ok in previous release?

**Comment by josd** [comment]
Well,
```
% test cases
case(type(_,n1)).
case(type(_,n10)).
case(type(_,n100)).
case(type(_,n1000)).
case(type(_,n10000)).
```
was always OK in all previous releases and
the I extended it the test cases to
```
% test cases
case(type(_,n1)).
case(type(_,n10)).
case(type(_,n100)).
case(type(_,n1000)).
case(type(_,n10000)).
case(type(_,i10000)).
case(type(_,j10000)).
```
and the seg fault suddenly happened :-(

**Comment by josd** [comment]
https://github.com/josd/eye/commit/61b96acafd7c00b9a774b12e77c8333acc9ba178

**Comment by josd** [comment]
You are the best programmer I have ever seen!

**Comment by infradig** [comment]
I have my moments. Fortunately I have had the pleasure (and still do) of
working with some truly talented people.

By the way, after realising I had totally stuffed up clause indexing, I
temporarily reverted to just indexing on the 1st arg. This had a bad affect
on your dt.pl program. Fortunately just reversing the args fixed that. I
have now added 2nd arg indexing as well so that's not necessary, though I
recommend doing it anyway for Prologs that don't do that (SWI does, GNU
doesn't).

:~/trealla$ time tpl -g "test." -f dt2.pl
type(n1,i).
type(n10,i).
type(n100,i).
type(n1000,i).
type(n10000,i).
type(i10000,i).
type(j10000,i).

real 0m0.361s
user 0m0.340s
sys 0m0.020s
:~/trealla$ time tpl -g "test." -f dt.pl
type(i,n1).
type(i,n10).
type(i,n100).
type(i,n1000).
type(i,n10000).
type(i,i10000).
type(i,j10000).

real 0m0.339s
user 0m0.319s
sys 0m0.020s

**Comment by josd** [comment]
Thanks Andrew and I understand - the reason is that type is actually
a predicate defined in https://www.w3.org/1999/02/22-rdf-syntax-ns#
and I can't change that definition :-)
I will make it explicit by using `rdf_type` and by adding
`namespace(rdf,'https://www.w3.org/1999/02/22-rdf-syntax-ns#').`
