### ISSUE TITLE
Top level: regression of answer layout:

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#357]
```
Trealla Prolog (c) Infradig 2020-2021, v1.18.31
?- length(_,I).
   I = 0 ;         % unexpected ;
   I = 1 ;
   I = 2 ;
   ...
```
In clauses ; is always written in front. And thus the same is very helpful at the top level.

**Comment by infradig** [comment]
Anything in particular you object to? The extra spaces after the comma will
go.

**Comment by UWN** [comment]
It used to be:
```
?- length(_,I).
   I = 0
;  I = 1
;  I = 2
;   ...
```

**Comment by infradig** [comment]
I like the new way, it leaves the semi-colon where you typed it. If this is
just a matter of personal preferences it doesn't really need to be an issue.

**Comment by UWN** [comment]
> it doesn't really need to be an issue.

So I will stop for now.

**Comment by triska** [comment]
The key motivation for writing `(;)/2` always at the start of a line instead of at the end is that `;` (semicolon) looks so similar to `,` (comma), and comma usually appears at the end of a line. Therefore, it is easy to misread a disjunction as a conjunction, if `;` is placed at the end of a line. 

For example the following output looks like a mistake at first sight (`X` is equal to `a` and also to `b` and `c`):

<pre>
<b>?- member(X, "abc").</b>
   X = a ;
   X = b ;
   X = c ;
   false.
</pre>

Whereas the following is much more preferable, since it uses the same layout that is strongly recommended and universally used in regular Prolog code:

<pre>
<b>?- member(X, "abc").</b>
   X = a
;  X = b
;  X = c
;  false.
</pre>

As an additional benefit of this layout, answers from the toplevel can be directly pasted as regular Prolog code, and are already formatted as expected.

One other benefit is that Prolog beginners that are familiar with C and other languages tend to write `;` at the end of a goal as they are used to in order to "terminate a statement". Following the Prolog layout conventions by placing the `;` in front of a goal helps to remove this mistaken association.

**Comment by triska** [comment]
That's perfectly understandable! It has nothing to do with the layout though: Emit a newline after the first answer substitution, so that we get:

<pre>
<b>?- member(X, "abc").</b>
   X = a
NOW WE ARE HERE: <b>;</b> for more solutions!
</pre>

**Comment by infradig** [comment]
I don't know of any Prolog that would do that.

**Comment by triska** [comment]
I meant that Trealla should be the first system that does it.

The suggestions @UWN has made also influenced the toplevel of several other Prolog systems over the last few years, including that of SWI-Prolog and Scryer Prolog, both of which&mdash;after his recommendations were incorporated&mdash;did something that no other Prolog system had ever done before: SWI-Prolog to turn the toplevel into residual goals that can always be pasted back as queries and to clearly indicate whether there are further solutions or not, and Scryer Prolog as the first system that uses the universally recommended layout for disjunctions also in answers. Treally could be the first Prolog system to emit an additional newline so that the `;` appears where it is entered!

**Comment by infradig** [comment]
I might try it and see how it feels.

**Comment by triska** [comment]
It looks very nice, thank you a lot!

In fact, this will be a huge improvement for longer outputs when using an Emacs frontend such as `ediprolog` to interact with Trealla. The reason is that for a query that produces a very long line as answer, Emacs would previously (i.e., with point at the end of a line) "scroll" horizontally and move point outside the regular viewing area, making the situation somewhat confusing.

Now, with this change applied, since a line break is automatically part of the output, we get to see the original query and all the buffer contents even if a very long line occurs as part of the answer, and only the remainder of the answer is outside the view. I think this yields more intuitive orientation and interaction especially when using Trealla with such frontends that are not themselves VT100 terminals.

Example:

<pre>
<b>?- (X = 1000 ; X = 2000), length(Ls, 1000).</b>
   X = 1000, Ls = [_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66|...]
;  X = 2000, Ls = [_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66|...].
</pre>

**Comment by josd** [comment]
This is really nice @infradig 
```
$ tpl
Trealla Prolog (c) Infradig 2020-2021, v1.18.36-3-g2b4b2
?- member(X, "abc").
   X = a
;  X = b
;  X = c
;  false.
?-
```
and so much thanks to @triska and @UWN.

Now it gives a boost to https://github.com/josd/heisenberg

**Comment by infradig** [comment]
I would add a -f to test script before filename.

**Comment by infradig** [comment]
Forget that about -f.

**Comment by UWN** [comment]
> <pre>?- (X = 1000 ; X = 2000), length(Ls, 1000).
>    X = 1000, Ls = [_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66|...]
> ;  X = 2000, Ls = [_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66|...].</pre>

Looks nice! Should the order in which answer substitutions appear make reading difficult as in:

```
?- length(Ls, 1000), (X = 1000 ; X = 2000).
   Ls = [_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66|...], X = 1000
;  Ls = [_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66|...], X = 2000.
```
..., use the 'directive' `_=` to get those variables in front: 

```
?- _=[X], length(Ls, 1000), (X = 1000 ; X = 2000).
   X = 1000, Ls = [_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67|...]
;  X = 2000, Ls = [_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,_31,_32,_33,_34,_35,_36,_37,_38,_39,_40,_41,_42,_43,_44,_45,_46,_47,_48,_49,_50,_51,_52,_53,_54,_55,_56,_57,_58,_59,_60,_61,_62,_63,_64,_65,_66,_67|...].
```

Minor: `?` produces many options of unwanted help (like e) and adds an extra empty line. Why not start help  with a % ?

Stopping a query

```
?- member(X,"abc").
   X = a
;
   ...
```

would ideally read

```
?- member(X,"abc").
   X = a
;  ... .
```

**Comment by infradig** [comment]
It can be tidied up.
