### ISSUE TITLE
Syntax: operator '|'

### ISSUE THREAD

**Issue by UWN** [infradig/trealla#366]
```
?- current_op(Pri,Fix,'|').
   Pri = 1100, Fix = xfy. % unexpected. Expected: Pri = 1105
?- T=[(a|b)].
   T = [a|b]. % unexpected. Expected as input
```

**Comment by pmoura** [comment]
ISO/IEC 13211-1:1995/Cor.2:2012(en) standard, section 8.14.4.4:

> An operator '|' shall be only an infix operator with priority greater than or equal to 1001.

What changed? I don't see any related updates in ISO/IEC 13211-1:1995/Cor 3:2017(en).

**Comment by UWN** [comment]
Please Paulo, could you reserve your comments to posts?

**Comment by pmoura** [comment]
For the Prolog systems I have access (latest versions):

* 1105: B-Prolog, GNU Prolog, SWI-Prolog, XSB, YAP
* 1100: Ciao Prolog, CxProlog, ECLiPSe, LVM, Trealla Prolog, Tau Prolog
* not pre-defined: JIProlog, Scryer Prolog, SICStus Prolog

Due to this diversity, the test I provide for this case in Logtalk is currently (after the above cited standard documents):

```logtalk
test(iso_current_op_3_45, true) :-
	(	{current_op(P, T, '|')} ->
		P >= 1001, infix(T)
	;	true
	).
```

More uniformity would certainly be welcome.

**Comment by infradig** [comment]
FWIW CxProlog is 1100.

**Comment by infradig** [comment]
I would favour/favor 1105.

**Comment by pmoura** [comment]
No reason or preference in my part for either 1100 or 1105. The main motivation for my original question above is about a possible need to update the test.

**Comment by infradig** [comment]
I should ask (everyone), what's the rationale for predefining it unless DCG
is built into the parser?

**Comment by triska** [comment]
Scryer Prolog *does* define the operator in its `library(dcgs)`:

https://github.com/mthom/scryer-prolog/blob/c60ada84212e349d4d70e176e63e3b3b1120fd41/src/lib/dcgs.pl#L2

That is, you get the operator `(|)/2` if you add the directive `:- use_module(library(dcgs)).` in your code. A key motivation for this operator is indeed to use `|` in DCGs for *disjunction*, since `|` is used for this purpose in [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) and other grammar formalisms. Scryer Prolog defines the operator with priority&nbsp;1105 in this library.

**Comment by pmoura** [comment]
CHR implementations also use it. ToyCHR (by Gregory J. Duck) assumes the operator. In the Logtalk port, I use 1105 if the operator is not defined. In the CHR (by Tom Schrijvers) distributed with SWI-Prolog and YAP, there's a commented out definition with 1100. Both cases seems to indicate that either priority is fine.

**Comment by jacobfriedman** [comment]
I agree with 1105. After reading the DCG draft in full today: why does s.7 state the operator is implementation-dependent, rather than >=1001?

Aside: if anyone has a full operator library for _BNFs, I'd like to see it. Adding another disjunction operator is downright confusing.

**Comment by triska** [comment]
The DCG draft leaves no doubt about the the definition of the operator, it states:

<pre>
<b>6.3 Terms</b>

Extend the operator table of subclause 6.3.4.4 of ISO/IEC 13211–1 as follows:

Priority Specifier Operator(s)
<b> 1105       xfy       ’|’</b>

NOTE — The operator (-->)/2, specified in subclause 6.3.4.4 of the ISO/IEC
13211–1 Prolog standard, is used as the principal functor of grammar rules.
</pre>

**Comment by pmoura** [comment]
I will update LVM to also 1105.

**Comment by jacobfriedman** [comment]
Ah, sorry it was for if-then-else: The use of (’|’)//2 instead of (;)//2 in an if-then-else, cf 7.14.5, shall be implementation-dependent. Kind of strange...

1105 is expected, then, as per the draft spec.

**Comment by UWN** [comment]
[N220](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/3steps).

**Comment by jfmc** [comment]
I will update Ciao to 1105 too. Thank you @pmoura for pushing this 👍

**Comment by jariazavalverde** [comment]
I'll add it to Tau Prolog with priority 1105. Thanks @pmoura!
