### ISSUE TITLE
Please consider using strings for file names and paths

### ISSUE THREAD

**Issue by triska** [infradig/trealla#86]
Please consider using strings (lists of characters) to represent paths and file names. The reason is that strings can be easily reasoned about with DCGs and predicates like `append/3` etc., and also that strings do not add any entries to the atom table.

The ISO standard permits this:

<pre>
       A source/sink is specified as an implementation defined
       ground term in a call of open/4 (8.11.5). All subsequent
       references to the source/sink are made by referring to a
       stream-term (7.10.2) or alias (7.10.2.2).
</pre>

**Comment by infradig** [comment]
Will do...

**Comment by pmoura** [comment]
There are no strings in Prolog. Only double-quoted terms whose interpretation depends on the problematic flag `double_quotes` flag. Atoms are portable (minus differences between system with escape sequences). Strings are not. Adding entries to the atom table is only an issue with atoms that are only used once (but then there are systems featuring atom garbage collectors). File paths are a good example only in the absence of a Prolog reflection API that allows tools (e.g. a make tool) and applications to query loaded files. Even when considering a single Prolog system, the simple fact that the Prolog `set_prolog_flag/2` directive is not specified to have **local** scope can easily break code. The way forward is not having everything working with double-quoted terms. True progress will be having a string type not depending on any flag, not trying to force systems and programmers to a context where `chars` is the only admissible value for the `double_quotes` flag.

**Comment by josd** [comment]
As far as I can read, the book "Prolog : the standard ; reference manual / Pierre Deransart" on page 229 mentions "Double quoted **string** term" being
```
term(T, P) --> double_quoted_list(DQL),
               rest_term(DQL, T, 0, P)
```

**Comment by pmoura** [comment]
@josd That's just a misleading sentence in that book. See the official ISO Prolog Core standard, section 6.3.7. It starts with:

> A double quoted list is either an atom (6.3.1.3) or a list (6.3.5).

The word "string" is not used anywhere in that section. Is also not in the standard glossary  (section 3).

**Comment by pmoura** [comment]
A simple example of code breaking using the latest `master` branch:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.92-1-g5862
?- current_prolog_flag(double_quotes, V).
 V = chars.
?- working_directory(Current, Current).
 Current = "/Users/pmoura/Documents/Prolog/trealla/".
?- absolute_file_name("$HOME", New, [expand(true)]),  working_directory(Old, New).
false.
?- working_directory(Current, Current).
 Current = "/Users/pmoura/".
```

The third goal should have succeeded but it failed instead. But the current directory was actually changed. As far as I can tell, the `double_quotes` flag is global. Let's say that in some code, the programmer is setting it to `codes` (also a standard value for the flag):

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.92-1-g5862
?- set_prolog_flag(double_quotes, codes).
true.
?- working_directory(Current, Current).
 Current = "/Users/pmoura/Documents/Prolog/trealla/".
?- absolute_file_name("$HOME", New, [expand(true)]),  working_directory(Old, New).
Error: uncaught exception... error(type_error(atom,.))
```

Oops. It seems that none of the above file-system access predicates can be called by passing double-quoted terms. But we did get a double-quoted term binding for our call to the `working_directory/2`... hum... what about:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.92-1-g5862
?- set_prolog_flag(double_quotes, codes).
true.
?- working_directory(Current, Current).
 Current = "/Users/pmoura/Documents/Prolog/trealla/".
?- working_directory(Current, Current), absolute_file_name(Current, Path).
 Current = "/Users/pmoura/Documents/Prolog/trealla/", Path = "/Users/pmoura/Documents/Prolog/trealla".
```

So... the user `"$HOME"` double-quoted term doesn't work but the system double-quoted term, `"/Users/pmoura/Documents/Prolog/trealla/"` works. Do I know exactly what's happening here? Of course. But that's not the point is it?

I guess the user can always use instead:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.92-1-g5862
?- set_prolog_flag(double_quotes, codes).
true.
?- working_directory(Current, Current).
 Current = "/Users/pmoura/Documents/Prolog/trealla/".
?-  atom_chars('$HOME', Chars), absolute_file_name(Chars, New, [expand(true)]),  working_directory(Old, New).
false.
?- working_directory(Current, Current).
 Current = "/Users/pmoura/".
```

That is, the only way to **safely** use any built-in predicates that now work with double-quoted terms is... to never use double-quoted terms explicitly when calling them (brilliant solution) **or** to consider the `double_quotes` flag as a read-only flag set to `chars` (and there goes standard compliance out of the window). Note that making the flag local to a file or to a module doesn't solve the problem illustrated here if the file or module still needs to call predicates such as `absolute_file_name /2-3` or `working_directory/2`.

Don't get me wrong. Prolog badly needs a string type. But that type should not depend on a flag so that problems as above cannot occur and safe and reliable code can be written and shared between systems. The second best thing here would be to kill the `double_quotes` flag (and, while at it, also kill the `unknown` flag; but I digress).

**Comment by infradig** [comment]
I was just looking at changing working_directory/2 to return an atom again.

**Comment by infradig** [comment]
Fix for working_directory/2, chdir() return value was inverted.

**Comment by triska** [comment]
The core problem in the examples posted is the nonsensical mixed interpretation of environment variables and verbatim&nbsp;text. This is no argument at all for or against using characters. It is a strong argument for separating the expansion of environment variables from predicates that reason about file names.

**Comment by pmoura** [comment]
Sigh. The problem occurs with **any** double-quoted term and have to do with the interpretation of double-quoted terms being dependent on a flag, not their actual content! Here is an example that have nothing to do with files or environment variables:

```text
 $ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.96-9-g1ba1
?- current_prolog_flag(double_quotes, V).
 V = chars.
?- use_module(library(format)).
true.
?- format("~w ~q~n", [a(A), a('A')]).
a(_0) a(A)
true.
```

But then:

```text
$ ./tpl
Trealla ProLog (c) Infradig 2020, v1.2.96-9-g1ba1
?- set_prolog_flag(double_quotes, codes).
true.
?- use_module(library(format)).
true.
?- format("~w ~q~n", [a(A), a('A')]).
Error: uncaught exception... error(domain_error(empty_list,[a(_215),a(A)]),format_//2)
false.
```

So, calling the `format/2-3` predicate using double-quoted arguments only works with a **fixed** value for the `double-quotes` flag, which is global in most Prolog systems (Trealla Prolog, Tau Prolog, SICStus Prolog, Scryer-Prolog also IIRC, ..., the list goes on).

Atoms provide in general a portable solution. But not in this case here:

```text
?- format('~w ~q~n', [a(A), a('A')]).
Error: uncaught exception... error(type_error(list,~w ~q~n),must_be/2)
false.
```

No point repeating here the arguments/explanations from the other example. Double-quoted terms are **not** strings. Not in the standard. Not in any compliant (or aspiring to be compliant) Prolog system.

**Comment by triska** [comment]
The first argument of `format/2` must be a **list of characters**.

This issue is about making file names and paths **lists of characters**.

The fact that the flag `double_quotes` affects the interpretation of double-quoted terms has nothing to do with any of these issues, and I would prefer to not discuss it in this issue.

**Comment by pmoura** [comment]
> The first argument of `format/2` must be a **list of characters**.

There's de facto standard for the `format/2-3` predicates. It accepts an atom in the first argument. Just because you decide against that in your own implementation of these predicates doesn't change the de facto standard.

> This issue is about making file names and paths **lists of characters**.

A change that requires either calling the file-system access predicates with a double-quoted term (e.g. `working_directory(_, "/Users")`) **or** to write a list of characters explicitly (e.g. `working_directory(_, ['/','U','s','e','r','s'])`). The first alternative is fragile due to the reliance on a fixed value for a user changeable flag. The second is a burden to the programmer (to say the least).

> The fact that the flag `double_quotes` affects the interpretation of double-quoted terms has nothing to do with any of these issues, and I would prefer to not discuss it in this issue.

You titled this issue (emphasis mine) "Please consider using **strings** for file names and paths". Again, there is no string concept in the ISO Prolog Core standard. Can you explain to us how to have file names and paths represented as **lists of characters** without the built-in predicates that take or return file names and paths being affected by the current value of the `double_quotes` flag? What's your practical solution here?

**Comment by triska** [comment]
As I noted in the description of this issue (please see words 4 to 7), I am using strings synonymously with *lists of characters* as they are used in the [README&nbsp;file](https://github.com/infradig/trealla) of this project. There is also no string concept in C, yet it's clear to most C&nbsp;programmers that arrays of characters are often called *strings* in&nbsp;C. Lists of characters are also called *strings* in Haskell. The Prolog standard itself sometimes alludes to strings in examples like `char_code(Str, 99)` in 8.16.6.4, suggesting at least a slight connotation between strings and characters.

If you insist on the use of atoms, then your example:

<pre>
working_directory(_, ['/','U','s','e','r','s'])
</pre>

can be easily written for instance as:

<pre>
atom_chars('/Users', Cs), working_directory(_, Cs)
</pre>

I have a question at this point: Is anyone here seriously interested in setting `double_quotes` to `codes` in actual, new applications that are written for any of the newer Prolog systems that are now emerging? I mean the new Prolog systems that compactly represent lists of characters as sequences of bytes in memory, thereby eschewing the overhead of compound terms that is sometimes mentioned as a disadvantage of lists of characters in other Prolog systems to justify their own ad hoc data structures that conceptually do not fit into the language at all? I seriously ask: Why would you do that instead of using lists of characters in new applications?

It is clear that there are existing Prolog applications that represent strings as lists of codes, and there is at least one system which (non-conformingly) does not support the value `chars` for the Prolog flag `double_quotes`. However, every time a new Prolog system arises, we get the opportunity to choose: Do we want to forfeit the advantages of new, more compact and more readable representations to forever accommodate applications that were created in just the first 40 or 50&nbsp;years of Prolog? Alternatively, do we want to promote more readable and more convenient ways of writing and using Prolog code, especially if it is also more efficient? With each new Prolog system that arises, I will at least propose for discussion the latter of these options.

As regards the practical solutions: It is clear that atoms *must* be supported in file operations like `open/3`, the examples given in the ISO&nbsp;standard demand that. To support lists of characters *too* has only one drawback: There is an overlap between atoms and lists, and that is the atom&nbsp;`[]` which is both an atom *and* a&nbsp;list.

Consequently, when you write for example `open([], ..., ...)` it is not clear whether the file `[]` or the empty file name should be opened. However, in all file systems I tested, an empty string is not admissible as a file&nbsp;name. Hence, I seriously ask: Is this problem serious enough to prevent the support of a much more versatile representation of file names and directories in the form of lists of characters? Versatile especially in the sense that DCGs and other predicates for lists can be used on them, and also in the sense that we can reason about *partially instantiated* lists, whereas atoms must always be fully instantiated.

**Comment by pmoura** [comment]
> As I noted in the description of this issue (please see words 4 to 7), I am using strings synonymously with _lists of characters_ as they are used in the [README file](https://github.com/infradig/trealla) of this project. There is also no string concept in C, yet it's clear to most C programmers that arrays of characters are often called _strings_ in C. Lists of characters are also called _strings_ in Haskell. The Prolog standard itself sometimes alludes to strings in examples like `char_code(Str, 99)` in 8.16.6.4, suggesting at least a slight connotation between strings and characters.

I fully agree with the common view of a *string* as a *list of characters*. Even as a *list of codes*. But, as I highlighted, the trouble with using a *list of characters* when calling a predicate is that representing it using a double-quoted term creates a dependency on the `double_quotes` flag, which is global in most systems. Thus, changes to this flag value can easily break code. An example using standard Prolog features:

```text
| ?- set_prolog_flag(double_quotes, atom).
yes

| ?- atom("But they told me this was a string!").
yes
```

> If you insist on the use of atoms, then your example:
> 
> working_directory(_, ['/','U','s','e','r','s'])
> can be easily written for instance as:
> 
> atom_chars('/Users', Cs), working_directory(_, Cs)

That's the obvious workaround. The programmer can do it. So does predicates such as `format/2-3`, `working_directory/2`, and others. Is this symmetrical? No. If in my code I write e.g.

```logtalk
..., format('~w: ~q~n', [Key, Value]), ...
```

my code is not affected by whatever is the value of the `double_quotes` flag at compilation/loading time. Atoms have a portability advantage that double-quoted terms don't share. Moreover, if a conversion between atoms and list of characters is required, then predicates like the ones mentioned above can easily due it.

> I have a question at this point: Is anyone here seriously interested in setting `double_quotes` to `codes` in actual, new applications that are written for any of the newer Prolog systems that are now emerging?

Why stop there? Why support a problematic flag at all? Why not simply remove it? Backwards compatibility aside, I would expect most if not all Prolog implementers to say good riddance to the `double_quotes` flag. With it gone, Prolog could finally move to having a *string* term type. This, of course, would be a compliance issue for the *current* standard. But standards that do not evolve, die. There's also a solution that would not break compliance and would keep the flag for backwards compatibility: promoting back-quoted terms to be the string term type. This is not a novel idea; some Prolog systems already explored it (IIRC, LPA Prolog systems, ECLiPSe, ...). The downside is that programmers familiar with other languages are used to see double-quoted terms as strings. But then again Prolog is different in other ways...

> I mean the new Prolog systems that compactly represent lists of characters as sequences of bytes in memory, thereby eschewing the overhead of compound terms that is sometimes mentioned as a disadvantage of lists of characters in other Prolog systems to justify their own ad hoc data structures that conceptually do not fit into the language at all? I seriously ask: Why would you do that instead of using lists of characters in new applications?

There's no reason the (great) progress you mention here in improving the representation and internal handling of lists of characters could not be achieved for atoms as well. As a side note, some systems already provide garbage collectors for atoms. Atoms are also a good representation for text that is used repeatedly (e.g. compiler/linter/... warnings and error messages).

> It is clear that there are existing Prolog applications that represent strings as lists of codes, and there is at least one system which (non-conformingly) does not support the value `chars` for the Prolog flag `double_quotes`. However, every time a new Prolog system arises, we get the opportunity to choose: Do we want to forfeit the advantages of new, more compact and more readable representations to forever accommodate applications that were created in just the first 40 or 50 years of Prolog? Alternatively, do we want to promote more readable and more convenient ways of writing and using Prolog code, especially if it is also more efficient? With each new Prolog system that arises, I will at least propose for discussion the latter of these options.

Is quite unfortunate that the only true portable value of the `double_quotes` flag is `codes`. But the move forward should be more bold than "just" starting using `chars` instead. The question for me is: are there any sensible cases/application where using codes instead of characters is necessary? But even if the answer is "yes", why would that require the existence of the `double_quotes` flag?

> As regards the practical solutions: It is clear that atoms _must_ be supported in file operations like `open/3`, the examples given in the ISO standard demand that. To support lists of characters _too_ has only one drawback: There is an overlap between atoms and lists, and that is the atom `[]` which is both an atom _and_ a list.
> 
> Consequently, when you write for example `open([], ..., ...)` it is not clear whether the file `[]` or the empty file name should be opened. However, in all file systems I tested, an empty string is not admissible as a file name. Hence, I seriously ask: Is this problem serious enough to prevent the support of a much more versatile representation of file names and directories in the form of lists of characters? Versatile especially in the sense that DCGs and other predicates for lists can be used on them, and also in the sense that we can reason about _partially instantiated_ lists, whereas atoms must always be fully instantiated.

My main concern here, as I hope I have made clear, is code *portability* and *resilience*. If most Prolog systems agree on killing the `double_quotes` flag, or, in alternative and as a transition step, make it read-only with its value fixed to `chars`, those concerns would no longer apply. Prolog could then settle on using `"..."` (or the back-quoted alternative) as a true term type and these discussions would be relegated to books on Prolog history and evolution.

**Comment by triska** [comment]
ECLiPSe is a good example of a system where file operations like `open/3` already support two different data&nbsp;types to represent file names: atoms, and also the system's custom "string" data type.

Please consider adopting such a dual approach in Trealla Prolog too, i.e., to support both atoms and lists of characters to represent file names,  and beyond that to use primarily lists of characters so that operations on them are most convenient.

If not, it's not that big a deal. However, it would be great to be able to use Prolog's primary strengths, especially reasoning about text with&nbsp;DCGs, in more programs, and to choose representations that make this possible.

**Comment by infradig** [comment]
Trealla already supports that for open and I believe all predicates that
accept a filename or path.

**Comment by infradig** [comment]
Of course I may have forgotten a few... i'll check through when I can.

**Comment by pmoura** [comment]
> Trealla already supports that for open and I believe all predicates that accept a filename or path.

For *input* arguments, that simplifies using them. But for *output* arguments (e.g. `working_directory/2` or `getenv/2`) I assume a *consistent* choice would be made between returning an atom or a list of characters?
